site_name: Proton-docs
theme: readthedocs
repo_url: https://github.com/SugarLam1207/Proton-docs-template

nav:
  - 主頁:
    - 閱讀須知: index.md
  - 第一章 - 硬件指引:
    - 硬件清單: hardwarelist.md
  - 網絡配置:
    - 路由器設置: networksetup.md
  - 服務器部署: 
    - 服務器初始化: serversetup.md
  - Tentacle配置:
    - Tentacle安裝: tentacleinstall.md
    - Tentacle配置: tentaclesetup.md
    - 一鍵發佈: oneclickdeployment.md
    - 驗證系統可用: verify.md
  - 其他設備:
    - 打印機: printersetup.md
    - 刷卡機: cardswipesetup.md
    - 錢箱: cashiersetup.md
    - 一體機: allinonesetup.md
  - 硬件常見問題:
    - 問題及解決方案: hardwareissues.md
  - 第二章 - 系統使用指引:
    - 快速入門: quickstart.md
    - 點餐管理: ordermanagement.md
    - 支付管理: paymentfunction.md
    - 第三方訂單管理: thirdpartyorders.md
    - 報表中心: reportcenter.md
  - 第三章 - 聯繫我們:
    - 技術支持: technicalsupport.md
