site_name: Proton-docs
theme: readthedocs
repo_url: https://github.com/SugarLam1207/Proton-docs-template

nav:
  - Home:
    - Index: index.md
  - Hardware Guide:
    - Hardware Checklist: hardwarelist.md
    - Server Setup: serversetup.md
    - Network Environment Setup: networkenvsetup.md
    - Server Deployment: serverdeployment.md
    - One click Deployment: oneclickdeployment.md
  - System Guide:
    - Quick start: quickstart.md
    - Employee Management and Permissions: employeemanagement.md
    - Order Management: ordermanagement.md
    - Payment Function: paymentfunction.md
    - Other Order Types: otherordertypes.md
    - Third-party Orders: thirdpartyorders.md
    - Report Center: reportcenter.md
    - Offline Mode: offlinemode.md
  - Advanced:
    - Flexible Menu: flexiblemenu.md
  - FAQ:
    - Common Issues: commonissues.md
    - Troubleshooting: troubleshooting.md
  - Contact Us:
    - Technical Support: technicalsupport.md
    - Feedback: feedback.md
